# Generated by Django 5.2 on 2025-12-09 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoletaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('emitida', 'Emitida'), ('anulada', 'Anulada')], default='borrador', max_length=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_comision', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tipo_gas', models.CharField(choices=[('envasado', 'Envasado'), ('natural', 'Natural')], max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cliente')),
                ('revendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.revendedor')),
            ],
        ),
        migrations.CreateModel(
            name='ComisionRevendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.boletaventa')),
                ('revendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.revendedor')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleBoleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comision_item', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sales.boletaventa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.producto')),
            ],
        ),
    ]
